// Parse the Flipper GUI BDF fonts into a compact TS module of glyph bitmaps,
// used by the glyph matcher to recover text from the 128x64 framebuffer.
//
// Fonts (must pixel-match what the Flipper firmware renders via u8g2):
//   haxrcorp4089 -> FontSecondary (most menu/list text)
//   helvB08      -> FontPrimary   (headers, highlighted item)
//   profont11    -> FontKeyboard  (monospace)
// Source BDFs vendored under fonts-src/ (from the lopaka Flipper designer).
//
// Output: src/font-data.ts. Run: node scripts/gen-fonts.mjs

import fs from 'node:fs'
import path from 'node:path'

const SRC_DIR = 'fonts-src'
const OUT = 'src/font-data.ts'
// name in output -> bdf filename (without ext)
const FONTS = {
  haxrcorp4089: 'haxrcorp4089',
  helvB08: 'helvB08',
  profont11: 'profont11',
}
const FIRST = 0x20
const LAST = 0x7e

/** Parse one BDF file into { ascent, descent, bbw, bbh, glyphs: {code: glyph} }. */
function parseBdf(text) {
  const lines = text.split(/\r?\n/)
  let ascent = 0
  let descent = 0
  let bbw = 0
  let bbh = 0
  const glyphs = {}
  let i = 0
  while (i < lines.length) {
    const line = lines[i]
    if (line.startsWith('FONT_ASCENT')) ascent = parseInt(line.split(/\s+/)[1], 10)
    else if (line.startsWith('FONT_DESCENT')) descent = parseInt(line.split(/\s+/)[1], 10)
    else if (line.startsWith('FONTBOUNDINGBOX')) {
      const p = line.split(/\s+/)
      bbw = parseInt(p[1], 10)
      bbh = parseInt(p[2], 10)
    } else if (line.startsWith('STARTCHAR')) {
      // collect this glyph
      let code = -1
      let dw = 0
      let bbox = null
      const rows = []
      i++
      for (; i < lines.length && !lines[i].startsWith('ENDCHAR'); i++) {
        const l = lines[i]
        if (l.startsWith('ENCODING')) code = parseInt(l.split(/\s+/)[1], 10)
        else if (l.startsWith('DWIDTH')) dw = parseInt(l.split(/\s+/)[1], 10)
        else if (l.startsWith('BBX')) {
          const p = l.split(/\s+/)
          bbox = { w: +p[1], h: +p[2], xo: +p[3], yo: +p[4] }
        } else if (l === 'BITMAP') {
          for (i++; i < lines.length && !lines[i].startsWith('ENDCHAR'); i++) {
            const hex = lines[i].trim()
            if (!hex) continue
            rows.push(parseInt(hex, 16))
          }
          break
        }
      }
      if (code >= FIRST && code <= LAST && bbox) {
        // Normalize each row to a left-aligned bitmask in the top (bytes*8) bits.
        // BDF rows are already MSB-first, left aligned, padded to whole bytes.
        const bytesPerRow = Math.ceil(bbox.w / 8)
        const rowBits = bytesPerRow * 8
        glyphs[code] = {
          w: bbox.w,
          h: bbox.h,
          xo: bbox.xo,
          yo: bbox.yo,
          dw,
          rowBits,
          rows, // each int holds rowBits bits, MSB = leftmost pixel
        }
      }
      continue
    }
    i++
  }
  return { ascent, descent, bbw, bbh, glyphs }
}

const out = {}
for (const [name, file] of Object.entries(FONTS)) {
  const p = path.join(SRC_DIR, `${file}.bdf`)
  const font = parseBdf(fs.readFileSync(p, 'utf8'))
  out[name] = font
  console.log(`${name}: ${Object.keys(font.glyphs).length} glyphs, ascent=${font.ascent} descent=${font.descent} bbox=${font.bbw}x${font.bbh}`)
}

const header = `// GENERATED by scripts/gen-fonts.mjs - do not edit.
// Flipper GUI bitmap fonts (ASCII ${FIRST}-${LAST}) for glyph matching.
//
// Glyph fields: w/h = bitmap size, xo/yo = BDF offsets (yo = bottom relative to
// baseline, +up), dw = advance width, rowBits = bits per packed row int,
// rows[r] = MSB-first bitmask (bit (rowBits-1-c) is column c).

export interface Glyph {
  w: number
  h: number
  xo: number
  yo: number
  dw: number
  rowBits: number
  rows: number[]
}
export interface BdfFont {
  ascent: number
  descent: number
  bbw: number
  bbh: number
  glyphs: Record<number, Glyph>
}
export const FONTS: Record<string, BdfFont> = `

fs.writeFileSync(OUT, header + JSON.stringify(out) + '\n')
console.log(`wrote ${OUT} (${fs.statSync(OUT).size} bytes)`)
